export const categories = {
  '/cleanse': {
    label: 'Cleansers',
    eyebrow: 'COSRX · Cleanse',
    product: 'Low pH Good Morning Gel Cleanser',
    description: 'Gentle gel cleanser for daily use',
    price: '£12.00',
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=400&h=500&fit=crop',
  },
  '/tone': {
    label: 'Toners & mists',
    eyebrow: 'COSRX · Toner',
    product: 'AHA/BHA Clarifying Treatment Toner',
    description: 'Exfoliating daily toner',
    price: '£15.00',
    image: 'https://images.unsplash.com/photo-1629198688000-71f23e745b6e?q=80&w=400&h=500&fit=crop',
  },
  '/essence': {
    label: 'Essences',
    eyebrow: 'COSRX · Essence',
    product: 'Advanced Snail 96 Mucin Power Essence',
    description: 'Repairing essence for dehydrated, stressed skin',
    price: '£13.99',
    image: 'https://images.unsplash.com/photo-1617897903246-719242758050?q=80&w=400&h=500&fit=crop',
  },
  '/serum': {
    label: 'Serums',
    eyebrow: 'COSRX · Serum',
    product: 'The Vitamin C 23 Serum',
    description: 'Highly concentrated vitamin c serum',
    price: '£22.00',
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?q=80&w=400&h=500&fit=crop',
  },
  '/mask': {
    label: 'Masks',
    eyebrow: 'COSRX · Mask',
    product: 'Ultimate Nourishing Rice Overnight Spa Mask',
    description: 'Intensive nourishing and brightening mask',
    price: '£18.00',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=400&h=500&fit=crop',
  },
  '/moisturise': {
    label: 'Moisturisers',
    eyebrow: 'COSRX · Moisturise',
    product: 'Oil-Free Ultra-Moisturizing Lotion',
    description: 'Daily moisturizer with birch sap',
    price: '£19.50',
    image: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?q=80&w=400&h=500&fit=crop',
  },
  '/spf': {
    label: 'Sun care',
    eyebrow: 'COSRX · SPF',
    product: 'Aloe Soothing Sun Cream SPF50+ PA+++',
    description: 'Soothing daily sun protection',
    price: '£14.50',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=400&h=500&fit=crop',
  },
  '/eye': {
    label: 'Eye care',
    eyebrow: 'COSRX · Eye',
    product: 'Advanced Snail Peptide Eye Cream',
    description: 'Nourishing and brightening eye cream',
    price: '£20.00',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=400&h=500&fit=crop',
  },
};

export const navigation = [
  ['Cleansers', '/cleanse'],
  ['Toners & mists', '/tone'],
  ['Essences', '/essence'],
  ['Serums', '/serum'],
  ['Masks', '/mask'],
  ['Moisturisers', '/moisturise'],
  ['Sun care', '/spf'],
  ['Eye care', '/eye'],
  ['Ingredient glossary', '/ingredients'],
];
