export const collections = [
  { title: 'Shop All', handle: 'all', count: 40, group: 'shop' },
  { title: 'Best Sellers', handle: 'best-sellers', count: 40, group: 'shop', description: 'Discover the Korean skincare products our customers love most.' },
  { title: 'Cleansers', handle: 'cleansers', count: 2, group: 'category', description: "Discover authentic Korean cleansers designed to remove makeup, excess oil and impurities while maintaining your skin's natural moisture barrier. Whether you're looking for a gentle daily cleanser or a deep cleansing formula, our collection features trusted Korean skincare brands loved worldwide. Shop authentic Korean cleansers in the UK at MIIKOREAN." },
  { title: 'Toners', handle: 'toners', count: 5, group: 'category', description: "Korean toners help hydrate, soothe and prepare your skin for the rest of your skincare routine. From calming toners for sensitive skin to hydrating formulas packed with nourishing ingredients, discover some of Korea's most loved skincare products. Shop authentic Korean toners with UK delivery." },
  { title: 'Serums', handle: 'serums', count: 8, group: 'category', description: 'Korean serums are designed to target specific skincare concerns including hydration, brightness, acne, uneven skin tone and skin barrier support. Discover effective Korean skincare serums featuring ingredients such as niacinamide, centella asiatica and hyaluronic acid.' },
  { title: 'Moisturisers', handle: 'moisturisers', count: 11, group: 'category', description: 'Keep your skin healthy and hydrated with authentic Korean moisturisers from trusted K-beauty brands. Whether you have dry, oily, combination or sensitive skin, our collection includes moisturisers designed to support long-lasting hydration and skin barrier health.' },
  { title: 'Sunscreen', handle: 'sunscreen', count: 3, group: 'category', description: 'Korean sunscreens are known for their lightweight feel, comfortable wear and advanced UV protection. Protect your skin every day with authentic Korean SPF products trusted by skincare enthusiasts around the world.' },
  { title: 'Face Masks', handle: 'face-masks', count: 0, group: 'category', description: 'Discover hydrating, soothing and brightening Korean face masks designed to leave your skin refreshed and glowing. From sheet masks to intensive treatment masks, explore authentic Korean skincare products from trusted brands.' },
  { title: 'Acne & Breakouts', handle: 'acne-breakouts', count: 8, group: 'concern', description: 'Discover Korean skincare products designed to help reduce blemishes, unclog pores and support clearer-looking skin. Shop cleansers, toners, serums and treatments for acne-prone skin.' },
  { title: 'Dry & Dehydrated Skin', handle: 'dry-dehydrated-skin', count: 4, group: 'concern', description: 'Deeply hydrate and nourish your skin with Korean skincare products designed to restore moisture and support a healthy skin barrier.' },
  { title: 'Sensitive Skin', handle: 'sensitive-skin', count: 13, group: 'concern', description: 'Gentle Korean skincare formulas created to soothe irritation and support sensitive skin without harsh ingredients.' },
  { title: 'Dull & Uneven Skin Tone', handle: 'dull-uneven-skin-tone', count: 1, group: 'concern', description: 'Brighten tired-looking skin and improve overall radiance with Korean skincare products designed to support an even complexion.' },
  { title: 'Redness & Irritation', handle: 'redness-irritation', count: 0, group: 'concern', description: 'Calm and comfort stressed skin with Korean skincare products designed to reduce the appearance of redness and support the skin barrier.' },
  { title: 'Fine Lines & Ageing', handle: 'fine-lines-ageing', count: 16, group: 'concern', description: 'Support smoother, firmer-looking skin with Korean skincare products formulated to target visible signs of ageing.' },
  { title: 'Dark Spots & Pigmentation', handle: 'dark-spots-pigmentation', count: 7, group: 'concern', description: 'Target stubborn dark spots, post-acne marks and uneven skin tone with Korean skincare designed to brighten, even and restore radiance.' },
  { title: 'Glowing Skin', handle: 'glowing-skin', count: 20, group: 'concern', description: 'Achieve radiant, healthy-looking skin with Korean skincare designed to boost hydration, brighten dull complexions and enhance your natural glow.' },
  { title: 'Beauty Of Joseon', handle: 'beauty-of-joseon', count: 3, group: 'brand' },
  { title: 'COSRX', handle: 'cosrx', count: 3, group: 'brand' },
  { title: 'Anua', handle: 'anua', count: 0, group: 'brand' },
  { title: 'SKIN1004', handle: 'skin1004', count: 1, group: 'brand' },
  { title: 'Round Lab', handle: 'round-lab', count: 1, group: 'brand' },
  { title: 'Isntree', handle: 'isntree', count: 0, group: 'brand' },
];

export const categories = Object.fromEntries(
  collections.map((collection) => [`/collections/${collection.handle}`, collection]),
);

export const navigation = [
  ['Cleansers', '/collections/cleansers'],
  ['Toners', '/collections/toners'],
  ['Serums', '/collections/serums'],
  ['Moisturisers', '/collections/moisturisers'],
  ['Sunscreen', '/collections/sunscreen'],
];

export const commerceProducts = [
  {
    handle: 'low-ph-good-morning-gel-cleanser',
    title: 'Low pH Good Morning Gel Cleanser',
    vendor: 'COSRX',
    category: 'Cleanse',
    type: 'Cleanser',
    description: 'Gentle gel cleanser for daily use',
    price: 12,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=900&h=1100&fit=crop',
    available: true,
    badges: ['Cruelty-free', 'Made in South Korea', 'PAO 12 months'],
    keyIngredients: ['Vitamin B3'],
    safety: { scpn: 'No', pao: '12 months', origin: 'South Korea' },
    subscriptionEligible: true,
    pairsWith: ['aha-bha-clarifying-treatment-toner', 'advanced-snail-96-mucin-power-essence', 'the-vitamin-c-23-serum', 'ultimate-nourishing-rice-overnight-spa-mask'],
  },
  {
    handle: 'aha-bha-clarifying-treatment-toner',
    title: 'AHA/BHA Clarifying Treatment Toner',
    vendor: 'COSRX',
    category: 'Tone',
    type: 'Toner',
    description: 'Exfoliating daily toner',
    price: 15,
    image: 'https://images.unsplash.com/photo-1629198688000-71f23e745b6e?q=80&w=900&h=1100&fit=crop',
    available: true,
    badges: ['Cruelty-free'],
    subscriptionEligible: true,
  },
  {
    handle: 'advanced-snail-96-mucin-power-essence',
    title: 'Advanced Snail 96 Mucin Power Essence',
    vendor: 'COSRX',
    category: 'Essence',
    type: 'Essence',
    description: 'Repairing essence for dehydrated, stressed skin',
    price: 13.99,
    image: 'https://images.unsplash.com/photo-1617897903246-719242758050?q=80&w=900&h=1100&fit=crop',
    available: true,
    badges: ['Cruelty-free'],
    subscriptionEligible: true,
  },
  {
    handle: 'the-vitamin-c-23-serum',
    title: 'The Vitamin C 23 Serum',
    vendor: 'COSRX',
    category: 'Serum',
    type: 'Serum',
    description: 'Highly concentrated vitamin c serum',
    price: 22,
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?q=80&w=900&h=1100&fit=crop',
    available: true,
    badges: ['Cruelty-free'],
    subscriptionEligible: true,
  },
  {
    handle: 'ultimate-nourishing-rice-overnight-spa-mask',
    title: 'Ultimate Nourishing Rice Overnight Spa Mask',
    vendor: 'COSRX',
    category: 'Mask',
    type: 'Mask',
    description: 'Intensive nourishing and brightening mask',
    price: 18,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=900&h=1100&fit=crop',
    available: true,
    badges: ['Cruelty-free'],
    subscriptionEligible: true,
  },
];

export const commerceProductByHandle = Object.fromEntries(
  commerceProducts.map((product) => [product.handle, product]),
);
